server:
	port: "8082"
	allowOrigins:
		- "*"
	timeout: 30 # Seconds
	bodyLimit: "10M" # MiB
	prefixPath: "/v1"

database:
	host: localhost
	port: 5432
	user: root
	password: toor
	dbname: bookapp
	sslmode: disable
	schema: public